"use client";
import { useState } from "react";
import type { FormSchemaType } from "@/lib/schema";
import { defaultCapture } from "@/lib/contacts";
import { validateFormReferences } from "@/lib/engine";
import { validateMarketing } from "@/lib/marketing";
import ScorecardResultsEditor from "./ScorecardResultsEditor";

const steps = ["Your quiz", "Questions", "Results", "Design", "Publish"];
export default function GuidedQuizEditor({ form, onChange, onAdvanced, onTheme, onPublish, onPreview, onSave, status, published }: {
  form: FormSchemaType; onChange: (form: FormSchemaType) => void;
  onAdvanced: () => void; onTheme: () => void; onPublish: () => void; onPreview: () => void; onSave: () => void;
  status: string; published: boolean;
}) {
  const [step, setStep] = useState(0);
  const [questionIndex, setQuestionIndex] = useState(0);
  const q = form.questions[Math.min(questionIndex, form.questions.length - 1)];
  const m = form.marketing;
  const capture = form.capture || { ...defaultCapture, marketingEnabled: false };
  // Answer IDs and rule targets stay stable; changed labels clear stale result explanations.
  function question(patch: Partial<typeof q>) { onChange({ ...form, questions: form.questions.map(x => x.id === q.id ? { ...x, ...patch } : x) }); }
  const field = (label: string, value: string, change: (value: string) => void, multiline = false) => <label className="block text-sm font-medium">{label}{multiline ? <textarea className="hq-input mt-2 w-full min-h-24" value={value} onChange={e => change(e.target.value)} /> : <input className="hq-input mt-2 w-full" value={value} onChange={e => change(e.target.value)} />}</label>;
  const issues: { text: string; step: number }[] = [];
  if (!form.title.trim()) issues.push({ text: "Give your quiz a title", step: 0 });
  if (!form.questions.length || form.questions.some(x => !x.title.trim() || x.options?.some(o => !o.label.trim()))) issues.push({ text: "Complete your questions and answer labels", step: 1 });
  try { validateFormReferences(form); validateMarketing(form, true); } catch (e) { issues.push({ text: e instanceof Error ? e.message : "Review your scoring", step: 2 }); }
  if (m?.kind !== "scorecard" && m?.outcomes.some(o => !o.ctaUrl)) issues.push({ text: "Add destination links to your results (recommended)", step: 2 });
  if (capture.enabled && !capture.privacyUrl) issues.push({ text: "Add your privacy-policy link before collecting details", step: 4 });
  return <main className="guided-studio flex-1 overflow-y-auto bg-[#faf8f4] px-4 py-6 sm:px-8"><div className="mx-auto max-w-3xl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-red-800">Guided builder</p><p role="status" className="mt-1 text-xs text-slate-600">{status} · {published ? "Published quiz" : "Draft—not public"}</p></div><button onClick={onAdvanced} className="hq-secondary">Full editor & advanced tools</button></header>
    <nav aria-label="Quiz setup steps" className="guided-steps my-7 flex flex-wrap gap-2">{steps.map((label, i) => <button key={label} aria-current={step === i ? "step" : undefined} onClick={() => setStep(i)} className={`rounded-full px-4 py-2 text-sm ${step === i ? "bg-red-800 text-white" : "border bg-white text-slate-600"}`}>{i + 1}. {label}</button>)}</nav>
    <section className="guided-sheet rounded-2xl border bg-white p-5 sm:p-8 space-y-6" aria-label={steps[step]}>
      {step === 0 && <><h1 className="text-3xl font-semibold">Give your quiz a clear promise.</h1><p className="text-slate-600">Tell people what they will discover. Your starting questions and scoring are already connected; edit them one step at a time.</p>{field("Quiz title", form.title, title => onChange({ ...form, title, coverPage: form.coverPage ? { ...form.coverPage, title } : undefined }))}{field("What will people discover?", form.description || "", description => onChange({ ...form, description, coverPage: form.coverPage ? { ...form.coverPage, subtitle: description } : undefined }), true)}<p className="text-sm text-slate-500">Using a template? Replace its example products and advice with your own before publishing.</p></>}
      {step === 1 && <><h1 className="text-3xl font-semibold">One question at a time.</h1><p className="text-slate-600">Edit the words, then see how each answer contributes to a result. Advanced tools let you add fields, branching, and more complex rules.</p>{q ? <><label className="block text-sm font-medium">Question<select className="hq-input mt-2 w-full" value={Math.min(questionIndex, form.questions.length - 1)} onChange={e => setQuestionIndex(Number(e.target.value))}>{form.questions.map((x, i) => <option key={x.id} value={i}>{i + 1}. {x.title || "Untitled question"}</option>)}</select></label>{field("Question wording", q.title, title => question({ title }))}{q.options?.map((option, index) => <fieldset key={option.id} className="rounded-xl border p-4 space-y-3"><legend className="px-1 text-xs font-semibold">Answer {index + 1}</legend>{field("Answer wording", option.label, label => onChange({ ...form, questions: form.questions.map(x => x.id === q.id ? { ...x, options: x.options?.map(o => o.id === option.id ? { ...o, label } : o) } : x), marketing: m ? { ...m, rules: m.rules.map(r => r.questionId === q.id && r.answerId === option.id ? { ...r, reason: "" } : r) } : undefined }))}{m ? <div className="space-y-2">{m.rules.filter(r => r.questionId === q.id && r.answerId === option.id).map(rule => <div key={rule.id} className="flex flex-wrap items-center gap-2 text-sm text-slate-600"><span>{rule.effect === "exclude" ? "Rules out" : m.kind === "scorecard" ? "Points toward" : "Recommends"}: <strong>{[...m.outcomes, ...m.categories].find(t => t.id === rule.targetId)?.title || "Missing result"}</strong></span>{rule.effect === "add" && <label className="flex items-center gap-2">Points<input aria-label={`Points for answer ${index + 1} toward ${[...m.outcomes, ...m.categories].find(t => t.id === rule.targetId)?.title}`} className="w-20 rounded border p-2" type="number" min={0} max={100} value={rule.points} onChange={e => { const points = Number(e.target.value); if (Number.isFinite(points) && points >= 0 && points <= 100) onChange({ ...form, marketing: { ...m, rules: m.rules.map(r => r.id === rule.id ? { ...r, points } : r) } }); }} /></label>}</div>)}{!m.rules.some(r => r.questionId === q.id && r.answerId === option.id) && <p className="text-xs text-slate-500">No points assigned. This answer does not favor a result.</p>}</div> : <p className="text-xs text-slate-500">Use the full editor to configure correct answers and knowledge-quiz scoring.</p>}</fieldset>)}</> : <button onClick={onAdvanced} className="hq-primary">Add your first question in the full editor</button>}<button onClick={onAdvanced} className="text-sm underline">Add questions or change answer-to-result rules</button></>}
      {step === 2 && <><h1 className="text-3xl font-semibold">Make every result useful.</h1><p className="text-slate-600">Explain what fits, give one useful next step, and add the page you want people to visit.</p>{m?.kind === "scorecard" ? <ScorecardResultsEditor marketing={m} onChange={marketing => onChange({ ...form, marketing })} /> : m ? m.outcomes.map((outcome, index) => { const update = (patch: Partial<typeof outcome>) => onChange({ ...form, marketing: { ...m, outcomes: m.outcomes.map(o => o.id === outcome.id ? { ...o, ...patch } : o) } }); return <details key={outcome.id} className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Result {index + 1}: {outcome.title}</summary><div className="mt-4 space-y-4">{field("Result name", outcome.title, title => update({ title }))}{field("Why this fits", outcome.description, description => update({ description }), true)}{field("Helpful advice", outcome.advice, advice => update({ advice }), true)}{field("Button text", outcome.ctaLabel, ctaLabel => update({ ctaLabel }))}{field("Destination link", outcome.ctaUrl, ctaUrl => update({ ctaUrl }))}</div></details>; }) : <button className="hq-secondary" onClick={onAdvanced}>Configure results in the full editor</button>}<button onClick={onAdvanced} className="text-sm underline">Advanced result design, videos, and conditions</button></>}
      {step === 3 && <><h1 className="text-3xl font-semibold">Make it feel like your brand.</h1><p className="text-slate-600">Choose a palette, then adjust colors, type, and spacing. Your quiz keeps its own theme when embedded on another website.</p><div className="rounded-xl border p-6" style={{ background: form.theme.backgroundColor, color: form.theme.textColor }}><h2 className="text-xl font-semibold">{form.title}</h2><p className="my-4">{form.questions[0]?.title}</p><span className="inline-block rounded-lg px-4 py-2 text-white" style={{ background: form.theme.primaryColor }}>Your quiz colors</span></div><button onClick={onTheme} className="hq-primary">Customize theme</button></>}
      {step === 4 && <><h1 className="text-3xl font-semibold">Check it. Try it. Share it.</h1><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={capture.enabled} onChange={e => onChange({ ...form, capture: { ...capture, enabled: e.target.checked } })} />Collect contact details</label>{capture.enabled && <div className="space-y-4"><p className="text-sm text-slate-600">Contact capture is {capture.required ? "required" : "optional"}. Marketing opt-in is {capture.marketingEnabled ? "enabled" : "off"}. Change the full capture settings in advanced tools.</p>{field("Privacy-policy link", capture.privacyUrl, privacyUrl => onChange({ ...form, capture: { ...capture, privacyUrl } }))}</div>}<div className="rounded-xl bg-stone-50 p-4"><h2 className="font-semibold">Your launch checklist</h2>{issues.length ? <ul className="mt-3 space-y-3">{issues.map((issue, i) => <li key={i}><button className="text-left text-sm text-red-800 underline" onClick={() => setStep(issue.step)}>{issue.text} →</button></li>)}</ul> : <p className="mt-3 text-sm text-green-800">Basic checks passed. Try every intended result before sharing.</p>}</div><p className="text-sm text-slate-600">Preview saves your latest changes first. Publishing runs the full checks and asks you to confirm before changing the live quiz.</p><div className="flex flex-wrap gap-3"><button onClick={onSave} className="hq-secondary">Save draft</button><button onClick={onPreview} className="hq-secondary">Save & preview</button><button onClick={onPublish} className="hq-primary">Review & publish</button></div>{published && <a className="block text-sm underline" href={`/play/${form.id}`} target="_blank" rel="noreferrer">Open published quiz →</a>}</>}
    </section><footer className="my-6 flex items-center justify-between gap-3"><button className="hq-secondary disabled:opacity-40" disabled={step === 0} onClick={() => setStep(s => s - 1)}>Back</button><span className="text-xs text-slate-500">Step {step + 1} of 5</span>{step < 4 ? <button className="hq-primary" onClick={() => setStep(s => s + 1)}>Continue →</button> : <button className="hq-secondary" onClick={onAdvanced}>More tools</button>}</footer>
  </div></main>;
}
