"use client";
import { ArrowRight, ArrowUpRight, BarChart3, GitBranch, Plus, ShoppingBag, Sparkles, Users } from "lucide-react";
import type { MarketingConfig } from "@/lib/marketing";
export default function WorkspaceWelcome({busy,onCreate,onAI,projectCount,publishedCount}:{busy:boolean;onCreate:(kind?:MarketingConfig['kind'])=>void;onAI:()=>void;projectCount:number;publishedCount:number}) {
  return <>
    <section aria-label="Welcome to pippi" className="workspace-intro">
      <div><p className="pippi-eyebrow">YOUR CONVERSATION STUDIO</p><h1>Good questions.<br/><span>Better connections.</span></h1><p className="workspace-intro-copy">Create a quiz that understands your audience.<br className="hidden sm:block"/> Turn what you learn into a more personal next step.</p><div className="flex flex-wrap gap-3 mt-7"><a href="/templates" className="hq-primary"><Plus size={17}/>Create a quiz<ArrowUpRight size={16}/></a><button disabled={busy} onClick={onAI} className="hq-secondary"><Sparkles size={16}/>Start with AI</button></div></div>
      <div className="workspace-overview" aria-label="Workspace overview"><div className="flex justify-between items-center"><p className="pippi-eyebrow">YOUR WORKSPACE</p><span className="workspace-status"><span/>Free account</span></div><div className="workspace-numbers"><div><strong>{projectCount}</strong><span>Total quizzes</span></div><div><strong>{publishedCount}</strong><span>Published</span></div><div><strong>{Math.max(0,projectCount-publishedCount)}</strong><span>In progress</span></div></div><div className="workspace-note"><GitBranch size={21}/><p><strong>Every answer is a direction.</strong><span>Questions → Understanding → A useful next step</span></p></div></div>
    </section>
    <section id="quiz-starters" className="mb-9 scroll-mt-8" aria-label="Marketing quiz templates"><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><h2 className="text-lg font-semibold tracking-tight">Start with a clear purpose</h2><a href="/templates" className="text-sm font-medium text-red-800 flex items-center gap-2">Explore templates<ArrowRight size={15}/></a></div><div className="grid md:grid-cols-3 gap-4">{([
      {kind:'product_finder',title:'Find their perfect fit',label:'Product finder',copy:'Guide shoppers to a product that fits their day.',icon:ShoppingBag},
      {kind:'scorecard',title:'Make the next step clear',label:'Scorecard',copy:'Turn answers into a useful, personalized action plan.',icon:BarChart3},
      {kind:'segmentation',title:'Understand what matters',label:'Audience quiz',copy:'Meet people where they are with a relevant result.',icon:Users},
    ] as const).map(({kind,title,label,copy,icon:Icon})=><button key={kind} disabled={busy} onClick={()=>onCreate(kind)} className="purpose-card"><span className="purpose-icon"><Icon size={21}/></span><span className="purpose-label">{label}</span><h3>{title}</h3><p>{copy}</p><span className="purpose-action">Customize starter<ArrowUpRight size={16}/></span></button>)}</div></section>
    <div className="workspace-toolstrip"><a href="/create/marketing"><Sparkles size={18}/><span><strong>Build from your business</strong><small>Audience, offer, and your own voice</small></span><ArrowUpRight size={16}/></a><a href="/experiments"><GitBranch size={18}/><span><strong>Learn what works</strong><small>Compare quiz versions with A/B tests</small></span><ArrowUpRight size={16}/></a></div>
    <div id="your-quizzes" className="scroll-mt-8 flex flex-wrap items-end justify-between gap-4 mb-6"><div><p className="pippi-eyebrow mb-2">YOUR LIBRARY</p><h2 className="text-2xl font-semibold tracking-tight">Conversations in the making</h2></div><button disabled={busy} onClick={()=>onCreate()} className="hq-secondary"><Plus size={16}/>Blank quiz</button></div>
  </>;
}
