"use client";
import Image from "next/image";
import { ArrowDown, ArrowRight, ArrowUpRight, BarChart3, Check, GitBranch, Plus, ShoppingBag, Sparkles, Users, WandSparkles } from "lucide-react";
import type { MarketingConfig } from "@/lib/marketing";
export default function WorkspaceWelcome({busy,onCreate,onAI,projectCount,publishedCount}:{busy:boolean;onCreate:(kind?:MarketingConfig['kind'])=>void;onAI:()=>void;projectCount:number;publishedCount:number}) {
  return <>
    <section aria-label="Welcome to Quiznick" className="relative overflow-hidden rounded-[28px] bg-[#f1ebe1] border border-[#e8e2d8] mb-12">
      <div className="grid lg:grid-cols-[1.05fr_1fr]">
        <div className="relative z-10 px-7 py-10 sm:p-12 lg:py-16">
          <p className="text-[11px] font-semibold uppercase tracking-[.2em] text-[#656259] flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-indigo-600"/> A little curiosity. A real connection.</p>
          <h1 className="mt-6 text-[42px] sm:text-[58px] xl:text-[68px] leading-[1.04] tracking-[-.055em] font-semibold text-[#242520]">Don’t just collect leads.<br/><span className="font-serif italic font-normal tracking-[-.045em] text-[#4a4cba]">Understand them.</span></h1>
          <p className="mt-6 max-w-md text-base sm:text-[17px] leading-relaxed text-[#66665f]">Turn a few thoughtful questions into a product they’ll love, a clearer next step, or a reason to choose you.</p>
          <div className="flex flex-wrap gap-3 mt-8"><button disabled={busy} onClick={()=>onCreate()} className="inline-flex items-center justify-center gap-3 rounded-full bg-[#272a27] hover:bg-[#454943] text-white px-6 py-3.5 text-sm font-medium transition disabled:opacity-50"><Plus size={17} aria-hidden="true"/>Create new quiz<ArrowUpRight size={17} aria-hidden="true"/></button><a href="#your-quizzes" className="inline-flex items-center gap-2 rounded-full px-4 py-3.5 text-sm font-medium text-[#454943] hover:bg-white/50">Your workspace<ArrowDown size={16} aria-hidden="true"/></a></div>
          <div className="flex flex-wrap gap-x-5 gap-y-2 mt-8 text-xs text-[#676960]"><span className="flex items-center gap-1.5"><Check size={14} aria-hidden="true"/>Personalized results</span><span className="flex items-center gap-1.5"><Check size={14} aria-hidden="true"/>Built-in analytics</span></div>
        </div>
        <div className="relative min-h-[310px] sm:min-h-[380px] lg:min-h-full">
          <Image src="/images/curiosity-still-life.webp" alt="Cobalt ribbon sculpture with translucent glass spheres in warm sunlight" fill priority sizes="(max-width: 1023px) 100vw, 50vw" className="object-cover object-right"/>
          <div className="absolute bottom-6 left-6 right-6 sm:left-8 sm:right-8 rounded-2xl bg-white/90 backdrop-blur-sm border border-white/80 p-4 shadow-sm flex gap-3 items-center"><span className="rounded-full bg-[#ecebfb] text-[#4a4cba] p-2.5"><GitBranch size={20} aria-hidden="true"/></span><div><p className="text-sm font-semibold text-[#343630]">Every answer is a direction.</p><p className="text-xs text-[#70716b] mt-0.5">Make the next step feel personal.</p></div></div>
        </div>
      </div>
    </section>
    <section id="quiz-starters" aria-label="Marketing quiz templates" className="scroll-mt-8 mb-10">
      <div className="flex flex-wrap justify-between items-end gap-4 mb-6"><div><p className="text-[10px] uppercase tracking-[.2em] text-indigo-600 font-semibold mb-2">Start with the outcome</p><h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-[#282a26]">What would you like to make happen?</h2></div><p className="text-xs text-slate-500 max-w-52">Editable starting points.<br/>Your questions. Your voice. Your offer.</p></div>
      <div className="grid md:grid-cols-3 gap-5">
        {([
          {kind:'product_finder',label:'Product finder',title:'Find their perfect fit.',copy:'Help shoppers cut through the options and discover a product that matches what matters to them.',icon:ShoppingBag,tint:'bg-[#f2eee5]',ink:'text-[#82724c]',sample:['Their preferences','A fitting recommendation']},
          {kind:'segmentation',label:'Buyer segmentation',title:'Make the next step personal.',copy:'Understand their priority, meet them where they are, and point them toward relevant help.',icon:Users,tint:'bg-[#eceefb]',ink:'text-[#6261b0]',sample:['Their biggest priority','A relevant next step']},
          {kind:'scorecard',label:'Category scorecard',title:'Give them a clearer picture.',copy:'Show people where they stand, what deserves attention, and how they can move forward.',icon:BarChart3,tint:'bg-[#eaf0e9]',ink:'text-[#587663]',sample:['Their current situation','An actionable scorecard']},
        ] as const).map(({kind,label,title,copy,icon:Icon,tint,ink,sample})=><button key={kind} disabled={busy} onClick={()=>onCreate(kind)} className="group text-left rounded-2xl bg-white border border-[#e4e5de] overflow-hidden transition hover:-translate-y-1 hover:shadow-lg hover:shadow-slate-200/50 focus-visible:outline-2 focus-visible:outline-indigo-500 disabled:opacity-50 motion-reduce:transform-none"><div className={`${tint} p-6 border-b border-black/5`}><div className="flex justify-between items-center"><span className={`inline-flex rounded-xl p-2.5 bg-white/80 ${ink}`}><Icon size={22} aria-hidden="true"/></span><span className={`text-[10px] uppercase font-semibold tracking-[.12em] ${ink}`}>{label}</span></div><div className="mt-6 flex items-center gap-2 text-xs text-[#62675e]"><span className="bg-white/85 border border-white rounded-lg px-2.5 py-2">{sample[0]}</span><ArrowRight size={14} className="shrink-0" aria-hidden="true"/><span className="leading-relaxed">{sample[1]}</span></div></div><div className="p-6"><h3 className="text-xl tracking-tight font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-500 min-h-[66px]">{copy}</p><span className="flex items-center justify-between mt-6 text-sm font-medium text-slate-800">Use this starting point<ArrowUpRight size={18} aria-hidden="true" className="group-hover:translate-x-0.5 transition"/></span></div></button>)}
      </div>
    </section>
    <section className="rounded-2xl border border-[#e4e5de] bg-white p-6 sm:p-7 flex flex-wrap items-center justify-between gap-6 mb-14" aria-label="AI quiz builder"><div className="flex items-start sm:items-center gap-4"><span className="rounded-2xl bg-[#f0ecfb] text-[#7262b1] p-3"><WandSparkles size={24} aria-hidden="true"/></span><div><h2 className="text-lg font-semibold tracking-tight">Big idea. Blank page. Let’s fix that.</h2><p className="text-sm text-slate-500 mt-1.5 max-w-lg">Describe your topic and audience. Get an editable quiz draft, then make it unmistakably yours.</p></div></div><button disabled={busy} onClick={onAI} className="inline-flex items-center gap-2 rounded-full border border-[#dcd9e9] hover:bg-[#f6f3fb] px-5 py-3 text-sm font-medium text-[#544488] disabled:opacity-50"><Sparkles size={16} aria-hidden="true"/>Create with AI<ArrowRight size={16} aria-hidden="true"/></button></section>
    <div id="your-quizzes" className="scroll-mt-8 flex flex-wrap items-end justify-between gap-4 mb-6"><div><p className="text-[10px] uppercase tracking-[.2em] text-indigo-600 font-semibold mb-2">Your workspace</p><h2 className="text-2xl sm:text-3xl font-semibold tracking-tight">Good conversations start here.</h2><p className="text-sm text-slate-500 mt-2">Pick up where you left off, or try your next idea.</p></div><div className="text-xs text-slate-500 flex gap-4"><span>{projectCount} {projectCount===1?'project':'projects'}</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>{publishedCount} published</span></div></div>
  </>;
}
